name: Check Package

on: 
  schedule:
    #- cron: '0 8 * * 5' # every friday AM 8:00
    - cron: '13 * * * *'
jobs:
  cocoapod:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - uses: MeilCli/carthage-update-check-action@master
      id: outdated
    - uses: 8398a7/action-slack@v2
      if: steps.outdated.outputs.has_carthage_update != 'false'
      with:
        status: ${{ job.status }}
        text: ${{ steps.outdated.outputs.carthage_update_text }}
        author_name: GitHub Actions
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
